kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test-th-077
  namespace: fleet-default
spec:
  repo: https://github.com/0xavi0/fleet-examples
  branch: helm-chart-deps
  pollingInterval: 35s
  paths:
  - test-th-077
  targets:
  # Match everything
  - clusterSelector: {}
