kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: test-th-086
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  pollingInterval: 35s
  paths:
  - test-th-086
  targets:
  # Match everything
  - clusterSelector: {}
