apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-preinstall-hang"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hang
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Pre-install hook started. Hanging forever..."
              sleep 360000
