apiVersion: v2
name: guestbook
description: Sample application
version: 0.0.0
appVersion: 0.0.0
dependencies:
- name: postgresql
  version: "13.4.3"
  repository: "https://charts.bitnami.com/bitnami"
