kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simple
  namespace: fleet-default
spec:
  repo: https://github.com/0xavi0/fleet-examples
  branch: test-multi-values
  pollingInterval: 10s
  paths:
  - values
  targets:
  # Match everything
  - clusterSelector: {}

