namespace: fleet-manifest-example
targets:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
  overlays:
  - noreplication

- name: test
  clusterSelector:
    matchLabels:
      env: test
  overlays:
  - scale3

- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  overlays:
  - servicelb
  - scale3
