apiVersion: v1
entries:
  configmap-chart:
  - apiVersion: v2
    created: "2026-03-31T14:32:02.209172+02:00"
    description: A test chart that deploys a single ConfigMap with a configurable
      name
    digest: 90e4968e151f266bdc19d709532d0d5ea1211898f2f21ea96001abebb0ab06c3
    name: configmap-chart
    type: application
    urls:
    - https://github.com/0xavi0/fleet-examples/raw/refs/heads/helm-chart-deps/charts/configmap-chart-0.1.0.tgz
    version: 0.1.0
  secret-chart:
  - apiVersion: v2
    created: "2026-03-31T14:32:02.209703+02:00"
    dependencies:
    - name: configmap-chart
      repository: https://github.com/0xavi0/fleet-examples/raw/refs/heads/helm-chart-deps/charts
      version: 0.1.0
    description: A test chart that deploys a single Secret with a configurable name
    digest: 3df13d892be9b7cc453d886f9923b16f03a8798a19b7b838f43d097c57a0fd74
    name: secret-chart
    type: application
    urls:
    - https://github.com/0xavi0/fleet-examples/raw/refs/heads/helm-chart-deps/charts/secret-chart-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-31T14:32:02.207721+02:00"
