apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: supercrds.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: Supercrd
    singular: supercrd
    plural: supercrds
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
