apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: megacrds.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: Megacrd
    singular: megacrd
    plural: megacrds
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
