apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-cert-manager
  namespace: cert-manager
spec:
  secretObjects:
    - secretName: vault-cert-manager-secrets
      type: Opaque
      data:
        - objectName: pro-hydrant
          key: secret
        - objectName: pro-cloudflare
          key: cloudflare_token
  parameters:
    vaultAddress: https://pwvault.pro.identrust.com
    vaultKubernetesMountPath: k8s-sec-prod
    objects: |
      - objectName: "pro-hydrant"
        secretPath: "kv-v2/data/cert-manager/sec-prod/acm"
        secretKey: "secret"
      - objectName: "pro-cloudflare"
        secretPath: "kv-v2/data/cert-manager/sec-prod/acm"
        secretKey: "cloudflare_token"