namespace: fleet-helm-example
targets:
- name: dev
  values:
    replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  values:
    replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  values:
    serviceType: LoadBalancer
    replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
